config/routes.rb
MailForever::Application.routes.draw do

  #static routes
  root to:'static_pages#home'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  #user routes
  match '/signup', to: 'users#new', via: 'get'

  resources :recipients
  resources :users do
    post 'login', on: :collection
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :recipients, through: :group_recipients
end

app/models/group_recipient.rb
class GroupRecipient < ActiveRecord::Base
  attr_accessible :group, :recipient
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :user_id
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  attr_accessible :deleted_at, :disabled_at, :recipient_email, :user_id
  belongs_to :user
  has_many :groups, through: :group_recipients

  def initialize attributes = {}
    @user_id = attributes[:user_id]
    @recipient_email = attributes[:recipient_email]
    @deleted_at = attributes[:deleted_at]
    @disabled_at = attributes[:disabled_at]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :hashed_password, :name
  validates_presence_of :email, :name, :hashed_password
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  
  has_many :recipients

  #TODO: salting
  def self.processed_password text_password
    if text_password
      Digest::MD5.hexdigest(text_password)
    end
  end

  def self.authenticate(options)
    email = options['email']
    password = options['hashed_password']
    if email && password
      user = User.where('email = ?', email).first
      if user && user.hashed_password == User.processed_password(password)
        user
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @recipients }
    end
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @recipient = Recipient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @recipient }
    end
  end

  # GET /recipients/new
  # GET /recipients/new.json
  def new
    @recipient = Recipient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @recipient }
    end
  end

  # GET /recipients/1/edit
  def edit
    @recipient = Recipient.find(params[:id])
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(params[:recipient])

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, :notice => 'Recipient was successfully created.' }
        format.json { render :json => @recipient, :status => :created, :location => @recipient }
      else
        format.html { render :action => "new" }
        format.json { render :json => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipients/1
  # PUT /recipients/1.json
  def update
    @recipient = Recipient.find(params[:id])

    respond_to do |format|
      if @recipient.update_attributes(params[:recipient])
        format.html { redirect_to @recipient, :notice => 'Recipient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.destroy

    respond_to do |format|
      format.html { redirect_to recipients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/signup
  # GET /users/signup.json
  def new
    @user = User.new
    errors = params['errors'].to_a
    errors.each{|e| @user.errors[:base] << e}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(filter_sign_up_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user.profile, :notice => "Welcome #{@user.name}!" }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        errors = @user.errors.full_messages
        format.html { redirect_to signup_path({errors: errors}), flash: {error: 'Invalid email or password.'}}
        format.json { render :json => {errors: @user.errors, type: 'register'}, :status => :unprocessable_entity }
      end
    end
  end

  # POST /users
  # POST /users.json
  def login
    respond_to do |format|
      if (User.authenticate(filter_login_params))
        format.html { redirect_to @user.profile, :notice => "Welcome #{@user.name}!" }
        format.json { render :json => @profile}
      else
       errors = ['Invalid email or password.']
       format.html { redirect_to signup_path({errors: errors}), :action => "new", notice: 'Invalid email or password.'}
       format.json { render :json => {errors: ['Invalid email or password.'], type: 'login'}, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def filter_sign_up_params
    processed_params = params.require(:user).permit(:name, :email)
    processed_params['hashed_password'] = User.processed_password(params[:user][:hashed_password])
    processed_params
  end

  def filter_login_params
    params['user'].slice(:email, :hashed_password)
  end

  def random_alphanumeric
    (0...8).map { (65 + rand(26)).chr }.join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title page_title = ''
    title_prefix = 'UniCloud'
    page_title.empty? ? title_prefix : (title_prefix + ' | ' + page_title) 
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_page/index.html.haml
%h1 Listing users
%table
  %tr
    %th Name
    %th Email
    %th User name
    %th Hashed password
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.hashed_password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/layouts/_footer.html.haml
%footer
  %nav
    %ul.list-inline.pull-right
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li= link_to "Help", help_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to image_tag("logo.jpg", :alt => "Rails"), root_path , :id => "logo"
      = link_to "UniCloud", root_path, :id => "logo"
      %nav
        %ul.nav.pull-right.list-inline
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          %li= link_to "Sign in", signup_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    .row
      .col-md-1
      .col-md-10
        = render 'layouts/header'
      .col-md-1
    %br
    %br
    %br
    .container
      .row
        .col-md-1
        .col-md-10
          = yield
        .col-md-1
    .row
      .col-md-1
      .col-md-10
        = render 'layouts/footer'
      .col-md-1

app/views/recipients/_form.html.erb
<%= form_for(@recipient) do |f| %>
  <% if @recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% @recipient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :recipient_email %><br />
    <%= f.text_field :recipient_email %>
  </div>
  <div class="field">
    <%= f.label :disabled_at %><br />
    <%= f.datetime_select :disabled_at %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br />
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table>
  <tr>
    <th>User</th>
    <th>Recipient email</th>
    <th>Disabled at</th>
    <th>Deleted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipients.each do |recipient| %>
  <tr>
    <td><%= recipient.user_id %></td>
    <td><%= recipient.recipient_email %></td>
    <td><%= recipient.disabled_at %></td>
    <td><%= recipient.deleted_at %></td>
    <td><%= link_to 'Show', recipient %></td>
    <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
    <td><%= link_to 'Destroy', recipient, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @recipient.user_id %>
</p>

<p>
  <b>Recipient email:</b>
  <%= @recipient.recipient_email %>
</p>

<p>
  <b>Disabled at:</b>
  <%= @recipient.disabled_at %>
</p>

<p>
  <b>Deleted at:</b>
  <%= @recipient.deleted_at %>
</p>


<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>

app/views/static_pages/about.html.haml
- provide(:title, 'About')
%h1 About
%p
  The mission of UniCloud is to provide users with sophisticated options to deal with all their cloud accounts and their contents.
  
  Please email sri149@gmail.com for any feedback or requests.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p Please email sri0149@gmail.com for help.

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p Please email to 'sri0149@gmail.com' if you need any assistance.

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 UniCloud 
  %h2
    One place to organize all your cloud accounts. Its easy and free to use.
    Just signup for free and dive in!
  = link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary"

app/views/users/_errors.html.haml
- if @user.errors.any?
  .panel.panel-warning
    .panel-heading Please correct the following error(s) : 
    %ul.list-gorup
      - @user.errors.full_messages.each do |msg|
        %li.list-group-item.error-message= msg 

app/views/users/_login_form.html.haml
=form_for @user, url: login_users_path, method: 'post',  html: {class: "user"} do |f|
  %br
  %h3
    Sign in
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :password
    %br
    = f.text_field :hashed_password
  .actions
    = f.submit 'Login', class:"btn btn-default"

app/views/users/_signup_form.html.haml
= form_for(@user) do |f|
  %br
  %h3 
    Not Yet Registered?
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.text_field :hashed_password
  .actions
    = f.submit 'Signup', class:"btn btn-default"

app/views/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th Name
    %th Email
    %th User name
    %th Hashed password
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= user.hashed_password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
- provide :title, 'Sign up'

%br 
= render 'errors'
.row
  .col-md-1
  .col-md-5
    = render 'login_form'
  .col-md-5
    = render 'signup_form'
  .col-md-1

app/views/users/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Hashed password:
  = @user.hashed_password
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}